spring.application.name=reserveerimisSusteem

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=840637
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
